/* 
 * API V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TestApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class TestApiTests
    {
        private TestApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new TestApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TestApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' TestApi
            //Assert.IsInstanceOfType(typeof(TestApi), instance, "instance is a TestApi");
        }

        
        /// <summary>
        /// Test ApiTestCleanupPost
        /// </summary>
        [Test]
        public void ApiTestCleanupPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ApiTestCleanupPost();
            
        }
        
        /// <summary>
        /// Test ApiTestPreparePost
        /// </summary>
        [Test]
        public void ApiTestPreparePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ApiTestPreparePost();
            
        }
        
    }

}
